settings:
  title: 'Status Page'
  url: 'https://uptime.workfor.live' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: jellyfin
    name: Jellyfin
    description: 'Jellyfin'
    url: 'https://jellyfin.workfor.live/health'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: false

  - id: vaultwarden
    name: Vaultwarden
    description: 'Vaultwarden'
    url: 'https://vaultwarden.workfor.live/alive'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: false

  - id: immich
    name: Immich
    description: 'Immich'
    url: 'https://immich.workfor.live/api/server-info/ping'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: false

  - id: outline
    name: Outline
    description: 'Outline'
    url: 'https://outline.workfor.live/_health'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: false

  - id: gitea
    name: Gitea
    description: 'Gitea'
    url: 'https://gitea.workfor.live/api/healthz'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: false
